###############################################################################
#
# GENERIC
#
###############################################################################

page-introduction:
    type: page-introduction
    dataPath: '${id}_introduction.html'
    query: >
        ${id}_introduction: markdownRemark(
            frontmatter: {
                type:   { eq: "introduction" }
                page:   { eq: "${id}" }
                locale: { eq: "en-US" }
            }
        ) {
            html
        }

###############################################################################
#
# DEMOGRAPHICS
#
###############################################################################

country:
    type: participation-by-country
    showDescription: true
    dataPath: 'surveyApi.demographics.country.0' # select the 4th array item to select the 4th year
    query: >
        surveyApi {
            demographics{
              country{
                year
                total
                completion{
                  percentage
                  count
                }
                buckets{
                  id
                  count
                  percentage
                }
              }
            }
        }

source:
    type: horizontal-bar
    showDescription: true
    dataPath: 'surveyApi.demographics.source.0' # select the 4th array item to select the 4th year
    query: >
        surveyApi {
            demographics{
              source{
                year
                total
                completion{
                  percentage
                  count
                }
                buckets{
                  id
                  count
                  percentage
                }
              }
            }
        }

# Used for salaries, company size, experience, etc. blocks
demographics-block:
    type: vertical-bar
    dataPath: 'surveyApi.demographics.${id}.2' # select the 4th array item to select the 4th year
    showDescription: true
    query: >
        surveyApi {
            demographics {
                ${id} {
                    year
                    total
                    completion {
                        percentage
                        count
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                }
            }
        }

gender-block:
    type: gender
    showDescription: true
    dataPath: 'surveyApi.demographics.gender.1'
    query: >
        surveyApi {
          demographics {
            gender {
              year
              total
              completion {
                percentage
                count
              }
              buckets {
                count
                id
                percentage
              }
            }
          }
        }

job-title-block:
    type: horizontal-bar
    dataPath: 'surveyApi.demographics.jobTitle.0'
    showDescription: true
    translateData: true
    query: >
        surveyApi {
          demographics{
            jobTitle{
              year
              total
              completion{
                count
                percentage
              }
              buckets{
                id
                count
                percentage
              }
            }
          }
        }

css-proficiency-block:
    type: vertical-bar
    dataPath: 'surveyApi.demographics.cssProficiency.0'
    showDescription: true
    showLegend: true
    query: >
        surveyApi {
          demographics{
            cssProficiency{
              year
              total
              completion{
                count
                percentage
              }
              buckets{
                id
                count
                percentage
              }
            }
          }
        }

backend-proficiency-block:
    type: vertical-bar
    dataPath: 'surveyApi.demographics.backendProficiency.0'
    showDescription: true
    showLegend: true
    query: >
        surveyApi {
          demographics{
            backendProficiency{
              year
              total
              completion{
                count
                percentage
              }
              buckets{
                id
                count
                percentage
              }
            }
          }
        }

###############################################################################
#
# TOOLS
#
###############################################################################

happiness-trend:
    type: happiness-trend
    dataPath: 'surveyApi.happiness_${pageId}.years'
    showDescription: true
    query: >
        surveyApi {
            happiness_${pageId}: happiness(id: ${pageId}) {
                years {
                    year
                    mean
                }
            }
        }

###############################################################################
#
# FEATURES
#
###############################################################################

# Used for destructuring, arrow functions, WebGL, etc.
feature:
    type: feature
    dataPath: 'surveyApi.${id}.usageByYear.0'
    showDescription: true
    query: >
        surveyApi {
            ${id}: feature(section: "${parentId}", id: ${id}) {
                id
                section
                usageByYear {
                    year
                    completion {
                        count
                        percentage
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                }
            }
        }

###############################################################################
#
# OPINIONS
#
###############################################################################

# Used for "I think JavaScript is moving in the right direction", etc. blocks
# {id} refers to the current subject
# this block renders a single year.
year-opinion:
    type: year-opinion
    dataPath: 'surveyApi.${id}.year'
    showDescription: true
    query: >
        surveyApi {
            ${id}: opinion(id: ${id}) {
                id
                year(year: ${currentYear}) {
                    year
                    completion {
                        count
                        percentage
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                }
            }
        }

###############################################################################
#
# OTHER TOOLS
#
###############################################################################

other-tools:
    type: horizontal-bar
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.${id}.year'
    query: >
        surveyApi {
            ${id}: otherTools(id: ${id}) {
                id
                year(year: ${currentYear}) {
                    year
                    buckets{
                        id
                        count
                        percentage
                        entity {
                          homepage
                        }
                    }
                }
            }
        }

###############################################################################
#
# RESOURCES
#
###############################################################################

resources:
    type: horizontal-bar
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.${id}.year'
    query: >
        surveyApi {
            ${id}: resources(id: ${id}) {
                id
                year(year: ${currentYear}) {
                    year
                    buckets{
                        id
                        count
                        percentage
                        entity {
                          homepage
                        }
                    }
                }
            }
        }
