# Used for salaries, company size, experience, etc. blocks
demographics-block: 
  type: vertical-bar
  dataPath: 'demographics.{id}.2' # select the 4th array item to select the 4th year
  bucketKeys: {id}
  showDescription: true
  query: >
      demographics {
        {id} {
          year
          total
          completion{
              percentage
              count
          }
          buckets {
            count
            id
            percentage
          }
        }
      }

# Used for destructuring, arrow functions, WebGL, etc.
feature: 
  type: feature
  dataPath: '{id}.usageByYear.0'
  showDescription: true
  query: >
    {id}: feature(section: "{parentId}", id: "{id}") {
      id
      section
      usageByYear {
        total
        year
        buckets {
          id
          count
          percentage
        }
        completion {
          percentage
          count
        }
      }
    }

# Used for "I think JavaScript is moving in the right direction", etc. blocks
opinion-scale: 
  type: opinion-scale
  dataPath: '{id}.byYear'
  # queryVariables: '$id: ID!'
  query: >
    {id}: opinion(id: "{id}") {
      id
      byYear {
        total
        year
        completion {
          percentage
          count
        }
      }
    }