###############################################################################
#
# GENERIC
#
###############################################################################

pageIntroductionTemplate:
    blockType: PageIntroductionBlock
    dataPath: '${pageId}_introduction.html'
    query: >
        ${pageId}_introduction: markdownRemark(
            frontmatter: {
                type:   { eq: "introduction" }
                page:   { eq: "${pageId}" }
                locale: { eq: "en-US" }
            }
        ) {
            html
        }

###############################################################################
#
# DEMOGRAPHICS
#
###############################################################################

# Used for salaries, company size, experience, etc. blocks that only show the current year of data
demographicsTemplate:
    blockType: VerticalBarBlock
    dataPath: 'surveyApi.survey.demographics.${id}.year' # select the 4th array item to select the 4th year
    showDescription: true
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                demographics {
                    ${id} {
                      year(year: ${currentYear}) {
                        year
                        total
                        completion {
                            percentage
                            count
                        }
                        buckets {
                            id
                            count
                            percentage
                        }
                      }
                    }
                }
            }
        }

###############################################################################
#
# TOOLS
#
###############################################################################

toolExperienceTemplate:
    blockType: ToolExperienceBlock
    dataPath: surveyApi.survey.tool.experience.allYears
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                tool(id: ${toolId}) {
                    id
                    entity{
                        name
                        homepage
                        npm
                        github
                    }
                    experience {
                      allYears{
                        year
                        total
                        completion {
                            count
                            percentage
                        }
                        awarenessInterestSatisfaction {
                            awareness
                            interest
                            satisfaction
                        }
                        buckets {
                            id
                            count
                            percentage
                        }
                      }
                    }
                }
            }
        }

heatmapTemplate:
    blockType: HeatmapBlock
    dataPath: 'surveyApi.survey.category.${heatmapId}.year'
    showDescription: true
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                category(id: ${sectionId}) {
                    ${heatmapId} {
                        year(year: ${currentYear}) {
                            year
                            buckets{
                                id
                                total
                                average
                                ranges{
                                    range
                                    count
                                    percentage
                                }
                            }
                        }
                    }
                }
            }
        }

happinessTemplate:
    blockType: HappinessBlock
    dataPath: 'surveyApi.survey.category.happiness.allYears'
    showDescription: true
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                category(id: ${sectionId}) {
                    happiness {
                        allYears {
                            year
                            mean
                        }
                    }
                }
            }
        }

###############################################################################
#
# FEATURES
#
###############################################################################

# Used for destructuring, arrow functions, WebGL, etc.
featureExperienceTemplate:
    blockType: FeatureExperienceBlock
    dataPath: 'surveyApi.survey.${id}.experience.year'
    showDescription: true
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                ${id}: feature(id: ${id}) {
                    id
                    experience{
                        year(year: ${currentYear}) {
                            year
                            completion {
                                count
                                percentage
                            }
                            buckets {
                                id
                                count
                                percentage
                            }
                        }
                    }
                }
            }
        }

###############################################################################
#
# OPINIONS
#
###############################################################################

# Used for "I think JavaScript is moving in the right direction", etc. blocks
# {id} refers to the current subject
opinionTemplate:
    blockType: OpinionBlock
    dataPath: 'surveyApi.survey.${id}.allYears'
    showDescription: true
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                ${id}: opinion(id: ${id}) {
                    id
                    allYears {
                        year
                        total
                        completion {
                            count
                            percentage
                        }
                        buckets {
                            id
                            count
                            percentage
                        }
                    }
                }
            }
        }

###############################################################################
#
# OTHER TOOLS
#
###############################################################################

otherToolsTemplate:
    blockType: HorizontalBarBlock
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.survey.${id}.year'
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                ${id}: otherTools(id: ${id}) {
                    id
                    year(year: ${currentYear}) {
                        year
                        buckets{
                            id
                            count
                            percentage
                            entity {
                              homepage
                            }
                        }
                    }
                }
            }
        }

###############################################################################
#
# RESOURCES
#
###############################################################################

resourcesTemplate:
    blockType: HorizontalBarBlock
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.survey.${id}.year'
    query: >
        surveyApi {
            survey(survey: ${surveyType}, year: ${currentYear}) {
                ${id}: resources(id: ${id}) {
                    id
                    year(year: ${currentYear}) {
                        year
                        buckets{
                            id
                            count
                            percentage
                            entity {
                              homepage
                            }
                        }
                    }
                }
            }
        }
