###############################################################################
#
# GENERIC
#
###############################################################################

page-introduction:
    type: page-introduction
    dataPath: '${id}_introduction.html'
    query: >
        ${id}_introduction: markdownRemark(
            frontmatter: {
                type:   { eq: "introduction" }
                page:   { eq: "${id}" }
                locale: { eq: "en-US" }
            }
        ) {
            html
        }

###############################################################################
#
# DEMOGRAPHICS
#
###############################################################################

# Used for salaries, company size, experience, etc. blocks that only show the current year of data
demographics-block:
    type: vertical-bar
    dataPath: 'surveyApi.demographics.${id}.year' # select the 4th array item to select the 4th year
    showDescription: true
    query: >
        surveyApi {
            demographics {
                ${id} {
                  year(year: ${currentYear}) {
                    year
                    total
                    completion {
                        percentage
                        count
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                  }
                }
            }
        }

###############################################################################
#
# TOOLS
#
###############################################################################

tool-opinions:
    type: opinions-over-time
    dataPath: surveyApi.tool.experience.allYears
    query: >
        surveyApi {
            tool(id: ${id}) {
                id
                experience {
                  allYears{
                    year
                    total
                    completion {
                        count
                        percentage
                    }
                    awarenessInterestSatisfaction {
                        awareness
                        interest
                        satisfaction
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                  }
                }
            }
        }

happiness-trend:
    type: happiness-trend
    dataPath: 'surveyApi.happiness_${pageId}.allYears'
    showDescription: true
    query: >
        surveyApi {
            happiness_${pageId}: happiness(id: ${pageId}) {
                allYears {
                    year
                    mean
                }
            }
        }

###############################################################################
#
# FEATURES
#
###############################################################################

# Used for destructuring, arrow functions, WebGL, etc.
feature:
    type: feature
    dataPath: 'surveyApi.${id}.year'
    showDescription: true
    query: >
        surveyApi {
            ${id}: feature(section: "${parentId}", id: ${id}) {
                id
                section
                year(year: ${currentYear}) {
                    year
                    completion {
                        count
                        percentage
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                }
            }
        }

###############################################################################
#
# OPINIONS
#
###############################################################################

# Used for "I think JavaScript is moving in the right direction", etc. blocks
# {id} refers to the current subject
opinion-block:
    type: opinion-scale
    dataPath: 'surveyApi.${id}.allYears'
    showDescription: true
    query: >
        surveyApi {
            ${id}: opinion(id: ${id}) {
                id
                allYears {
                    year
                    total
                    completion {
                        count
                        percentage
                    }
                    buckets {
                        id
                        count
                        percentage
                    }
                }
            }
        }

###############################################################################
#
# OTHER TOOLS
#
###############################################################################

other-tools:
    type: horizontal-bar
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.${id}.year'
    query: >
        surveyApi {
            ${id}: otherTools(id: ${id}) {
                id
                year(year: ${currentYear}) {
                    year
                    buckets{
                        id
                        count
                        percentage
                        entity {
                          homepage
                        }
                    }
                }
            }
        }

###############################################################################
#
# RESOURCES
#
###############################################################################

resources:
    type: horizontal-bar
    showDescription: true
    mode: absolute
    dataPath: 'surveyApi.${id}.year'
    query: >
        surveyApi {
            ${id}: resources(id: ${id}) {
                id
                year(year: ${currentYear}) {
                    year
                    buckets{
                        id
                        count
                        percentage
                        entity {
                          homepage
                        }
                    }
                }
            }
        }
