###############################################################################
#
# DEMOGRAPHICS
#
###############################################################################

# Used for salaries, company size, experience, etc. blocks
demographics-block:
    type: vertical-bar
    dataPath: 'demographics.${id}.2' # select the 4th array item to select the 4th year
    showDescription: true
    query: >
        demographics {
            ${id} {
                year
                total
                completion {
                    percentage
                    count
                }
                buckets {
                    id
                    count
                    percentage
                }
            }
        }

# Used for destructuring, arrow functions, WebGL, etc.
feature:
    type: feature
    dataPath: '${id}.usageByYear.0'
    showDescription: true
    query: >
        ${id}: feature(section: "${parentId}", id: "${id}") {
            id
            section
            usageByYear {
                year
                completion {
                    count
                    percentage
                }
                buckets {
                    id
                    count
                    percentage
                }
            }
        }

# Used for "I think JavaScript is moving in the right direction", etc. blocks
# {id} refers to the current subject
opinion-scale:
    type: opinion-scale
    dataPath: '${id}.byYear'
    showDescription: true
    query: >
      ${id}: opinion(id: "${id}") {
        id
        byYear {
          total
          year
          completion {
            count
            percentage
          }
          buckets {
            id
            count
            percentage
          }
        }
      }

other-tools:
  type: horizontal-bar
  showDescription: true
  mode: absolute
  dataPath: '${id}.year'
  query: >
    ${id}: otherTools(id: "${id}"){
      id
      year(year: ${currentYear}){
        year
        buckets{
          id
          count
          percentage
          homepage
        }
      }
    }

resources:
  type: horizontal-bar
  showDescription: true
  mode: absolute
  dataPath: '${id}.year'
  query: >
    ${id}: resources(id: "${id}"){
      id
      year(year: ${currentYear}){
        year
        buckets{
          id
          count
          percentage
          homepage
        }
      }
    }
