# define tools symbol
tools:
    typescript: Ts
    flow: Fw
    clojurescript: Cj
    reason: Re
    purescript: Ps
    babel: Bb
    coffeescript: Cs
    vuejs: V
    react: R
    angular: Ng
    backbone: Bb
    ember: Em
    preact: Pr
    hyperapp: Ha
    inferno: In
    svelte: Sv
    redux: Rd
    relay: Ry
    apollo: Ap
    mobx: Mx
    flux: Fx
    webpack: Wp
    gulp: Gu
    parcel: Pc
    rollup: Ru
    broccoli: Br
    express: Ex
    meteor: Me
    nextjs: Nx
    gatsby: G
    koa: Ko
    sails: Sa
    loopback: Lb
    socketio: Sk
    vulcan: Vn
    hapi: Ha
    feathers: Fe
    storybook: Sb
    jest: Je
    mocha: Mo
    ava: Av
    enzyme: Ez
    jasmine: Ja
    karma: Ka
    cypress: Cy
    puppeteer: Pp
    json-server: Js
    nightmare: Nm
    reactnative: Rn
    electron: E
    ionic: Io
    nativescript: Ns
    weex: We
    nwjs: Nw
    cordova: Cv
    phonegap-cordova: Cv
    d3: D
    jquery: Jq
    moment: Mt
    lodash: Lo
    underscore: Un
    ramda: Ra
    axios: Ax
    threejs: Th
    graphql: Gq
    polymer: Po
    elm: El
    es6: E6
    nativeapps: Na
    vuex: Vx
    visual-studio: Vs
    # not really tools but who cares
    arrow_functions: Af
    promises: Pr
    spread_operator: Sp
    stack_overflow: So
    mdn: Md
    css_tricks: Ct
    stencil: St
    nest: Ne

utilities:
    projects:
        - symbol: Ch
          id: chartjs
        - symbol: Ec
          id: echarts
        - symbol: Pt
          id: prettier
        - symbol: Im
          id: immutable
        - symbol: An
          id: animejs
        - symbol: Md
          id: modernizr
        - symbol: Rx
          id: rxjs

ui:
    projects:
        - symbol: Bs
          id: bootstrap
        - symbol: Su
          id: semanticui
        - symbol: Mu
          id: material-ui
        - symbol: An
          id: ant-design
        - symbol: Et
          id: element
        - symbol: Fd
          id: foundation

ssg:
    projects:
        - symbol: G
          id: gatsby
        - symbol: Hx
          id: hexo
        - symbol: Vp
          id: vuepress
        - symbol: Ms
          id: metalsmith
        - symbol: Rs
          id: react-static
        - symbol: Hp
          id: harp
