- id: introduction
  path: /
  type: page

- id: tshirt
  path: /tshirt
  type: page

- id: demographics
  path: /demographics
  type: page
  blocks:
      - id: participation-by-country
        type: participation-by-country
        showDescription: true
      - id: salary
        template: demographics-block
      - id: yearsOfExperience
        template: demographics-block
      - id: companySize
        template: demographics-block
      - id: source
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
      - id: gender
        type: gender
        showDescription: true
        dataPath: 'demographics.gender.1'
        query: >
            demographics {
              gender {
                year
                total
                completion {
                  percentage
                  count
                }
                buckets {
                  count
                  id
                  percentage
                }
              }
            }
      - id: job-title
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
        translateData: true
      - id: css-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeysN: cssProficiency
        showDescription: true
        showLegend: true
      - id: backend-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: backendProficiency
        showDescription: true
        showLegend: true
      - id: resources-sponsors
        type: resources
        items:
            - frontendmasters-design

- id: features
  path: /features
  type: page
  children:
      - id: syntax
        path: /syntax
        blocks:
            - id: syntax
              template: page-introduction

            - id: destructuring
              template: feature

            - id: spread_operator
              template: feature

            - id: arrow_functions
              template: feature

      - id: language
        path: /language
        blocks:
            - id: language
              template: page-introduction

            - id: proxies
              template: feature

            - id: async_await
              template: feature

            - id: promises
              template: feature

            - id: decorators
              template: feature

      - id: data_structures
        path: /data-structures
        blocks:
            - id: data_structures
              template: page-introduction

            - id: maps
              template: feature

            - id: sets
              template: feature

            - id: typed_arrays
              template: feature

            - id: array_prototype_flat
              template: feature

      - id: browser_apis
        path: /browser-apis
        blocks:
            - id: browser_apis
              template: page-introduction

            - id: fetch
              template: feature

            - id: i18n
              template: feature

            - id: local_storage
              template: feature

            - id: service_workers
              template: feature

            - id: web_animations
              template: feature

            - id: web_audio
              template: feature

            - id: web_components
              template: feature

            - id: webgl
              template: feature

            - id: webrtc
              template: feature

            - id: websocket
              template: feature

            - id: web_speech
              template: feature

            - id: webvr
              template: feature

      - id: other_features
        path: /other-features
        blocks:
            - id: features_other_features
              template: page-introduction

            - id: pwa
              template: feature

            - id: wasm
              template: feature

# - id: features
#   path: /features
#   type: page
#   defaultBlockType: feature
#   blocks:
#       - id: features-overview
#         type: features-overview
#   children:
#       - id: layout
#         path: /layout
#         type: features
#         data:
#             section: layout
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#             - id: layout-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - css-grid
#             - flexbox
#             - css-multi-column
#             - css-writing-modes
#             - css-exclusions
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - designcode1
#                   - frontendmasters-grid

#       - id: shapes-and-graphics
#         path: /shapes-and-graphics
#         type: features
#         data:
#             section: shapes-and-graphics
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#             - id: shapes-and-graphics-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - css-shapes
#             - object-fit
#             - clip-path
#             - css-masks
#             - blend-modes
#             - css-filter-effects
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-svg

#       - id: interactions
#         path: /interactions
#         type: features
#         data:
#             section: interactions
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#             - id: interactions-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - css-scroll-snap
#             - overscroll-behavior
#             - overflow-anchor

#       - id: typography
#         path: /typography
#         type: features
#         data:
#             section: typography
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#             - id: typography-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - web-fonts-font-face
#             - variable-fonts
#             - line-breaking-properties
#             - font-variant
#             - initial-letter
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-typography

#       - id: animations-and-transforms
#         path: /animations-and-transforms
#         type: features
#         data:
#             section: animations-and-transforms
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#             - id: animations-and-transforms-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - css-transitions
#             - css-transforms
#             - css-animations
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-css

#       - id: other-features
#         path: /other-features
#         type: features
#         data:
#             section: other-features
#         blocks:
#             - id: features-section-overview
#               type: features-section-overview
#               showDescription: true
#             - id: other-features-experience-heatmap
#               type: heatmap
#               subject: features
#               heatmapType: experience
#             - css-variables
#             - support-queries
#             - css-containment
#             - will-change
#             - calc
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - designcode2

- id: front_end_frameworks
  path: /front-end-frameworks
  template: toolSection
  children:
      - id: react
        template: tool
      - id: vue
        template: tool
      - id: angular
        template: tool
      - id: preact
        template: tool
      - id: ember
        template: tool
      - id: svelte
        template: tool
      - id: frontend-other
        template: other
      - id: frontend-conclusion
        template: conclusion

- id: data_layer
  path: /data-layer
  template: toolSection
  children:
      - id: redux
        template: tool
      - id: apollo
        template: tool
      - id: graphql
        template: tool
      - id: relay
        template: tool
      - id: mobx
        template: tool
      - id: datalayer-other
        template: other
      - id: datalayer-conclusion
        template: conclusion

- id: back_end_frameworks
  path: /back-end
  template: toolSection
  children:
      - id: express
        template: tool
      - id: nextjs
        template: tool
      - id: koa
        template: tool
      - id: meteor
        template: tool
      - id: sails
        template: tool
      - id: feathers
        template: tool
      - id: nuxt
        template: tool
      - id: gatsby
        template: tool
      - id: backend-other
        template: other
      - id: backend-conclusion
        template: conclusion

- id: testing
  path: /testing
  template: toolSection
  children:
      - id: jest
        template: tool
      - id: mocha
        template: tool
      - id: storybook
        template: tool
      - id: cypress
        template: tool
      - id: enzyme
        template: tool
      - id: ava
        template: tool
      - id: jasmine
        template: tool
      - id: puppeteer
        template: tool
      - id: testing-other
        template: other
      - id: testing-conclusion
        template: conclusion

- id: mobiledesktop
  path: /mobile-desktop
  template: toolSection
  children:
      - id: electron
        template: tool
      - id: react-native
        template: tool
      - id: native-apps
        template: tool
      - id: cordova
        template: tool
      - id: ionic
        template: tool
      - id: nwjs
        template: tool
      - id: expo
        template: tool
      - id: mobiledesktop-other
        template: other
      - id: mobiledesktop-conclusion
        template: conclusion

# - id: technologies
#   path: /technologies
#   type: page
#   defaultBlockType: tool
#   blocks:
#       - id: tools-overview
#         type: tools-overview
#       - id: tools-scatterplot
#         type: tools-scatterplot
#   children:
#       - id: frontend
#         path: /front-end
#         type: tools
#         blocks:
#             - id: frontend-section-overview
#               type: tools-section-overview
#             - id: frontend-experience-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: experience
#             - id: frontend-salary-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: salary
#             - react
#             - vue
#             - angular
#             - preact
#             - ember
#             - svelte
#             - id: other-frontend
#               type: other
#             - id: happiness-frontend
#               type: happiness
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-sass
#       - id: datalayer
#         path: /data-layer
#         type: tools
#         blocks:
#             - id: datalayer-section-overview
#               type: tools-section-overview
#             - id: datalayer-experience-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: experience
#             - id: datalayer-salary-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: salary
#             - redux
#             - apollo
#             - graphql
#             - mobx
#             - relay
#             - id: other-datalayer
#               type: other
#             - id: happiness-datalayer
#               type: happiness
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-sass

#       - id: css-in-js
#         path: /css-in-js
#         type: tools
#         blocks:
#             - id: tools-section-overview
#               type: tools-section-overview
#             - id: css-in-js-experience-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: experience
#             - id: css-in-js-salary-heatmap
#               type: heatmap
#               subject: tools
#               heatmapType: salary
#             - styled-components
#             - glamor
#             - aphrodite
#             - jss
#             - styled-jsx
#             - radium
#             - emotion
#             - css-modules
#             - id: resources-sponsors
#               type: resources
#               items:
#                   - frontendmasters-react

- id: other-tools
  path: /other-tools
  type: page
  blocks:
      - id: utilities
        template: other-tools
      - id: utilities_others
        template: other-tools
        mode: relative
        units: count
      - id: text_editors
        template: other-tools
      - id: text_editors_others
        template: other-tools
        mode: relative
        units: count
      - id: browsers
        template: other-tools
      - id: browsers_others
        template: other-tools
        mode: relative
        units: count
      - id: build_tools
        template: other-tools
      - id: build_tools_others
        template: other-tools
        mode: relative
        units: count
      - id: non_js_languages
        template: other-tools
      - id: non_js_languages_others
        template: other-tools
        mode: relative
        units: count

- id: resources
  path: /resources
  type: page
  blocks:
      - id: blogs_magazines
        template: resources
      - id: blogs_magazines_others
        template: resources
        mode: relative
        units: count
      - id: sites_courses
        template: resources
      - id: sites_courses_others
        template: resources
        mode: relative
        units: count
      - id: podcasts
        template: resources
      - id: podcasts_others
        template: resources
        mode: relative
        units: count
      - id: resources-sponsors
        type: resources
        items:
            - storybook1

- id: opinions
  path: /opinions
  type: page
  blocks:
      - id: opinions
        template: page-introduction
      - id: js_moving_in_right_direction
        template: opinion-scale
      - id: building_js_apps_overly_complex
        template: opinion-scale
      - id: js_over_used_online
        template: opinion-scale
      - id: enjoy_building_js_apps
        template: opinion-scale
      - id: would_like_js_to_be_main_lang
        template: opinion-scale
      - id: js_ecosystem_changing_to_fast
        template: opinion-scale
      - id: missing-features
        type: horizontal-bar
        dataKey: features

- id: awards
  path: /awards
  type: page
  blocks:
      - id: feature_adoption
        type: award
      - id: tool_usage
        type: award
      - id: tool_satisfaction
        type: award
      - id: tool_interest
        type: award
      - id: resource_usage
        type: award

- id: conclusion
  path: /conclusion
  type: page
  blocks:
      - id: conclusion
        type: text

# - id: support
#   path: /support
#   type: page
#   is_hidden: true

- id: notfound
  path: /404
  type: page
  is_hidden: true
