- id: introduction
  path: /
  type: page

- id: tshirt
  path: /tshirt
  type: page

- id: demographics
  path: /demographics
  type: page
  blocks:
      - id: participation-by-country
        type: participation-by-country
        showDescription: true
      - id: salary
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: salary
        showDescription: true
      # - id: salary-per-country
      #   type: countries
      - id: years-of-experience
        dataKey: breakdown
        type: vertical-bar
        bucketKeys: yearsOfExperience
        showDescription: true
      - id: company-size
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: companySize
        showDescription: false
      - id: source
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
      - id: gender
        type: gender
        showDescription: true
      - id: job-title
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
        translateData: true
      - id: javascript-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: javascriptProficiency
        showDescription: true
        showLegend: true
      - id: backend-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: backendProficiency
        showDescription: true
        showLegend: true
      - id: resources-sponsors
        type: resources
        items:
            - frontendmasters-design

- id: features
  path: /features
  type: page
  defaultBlockType: feature
  blocks:
      - id: features-overview
        type: features-overview
  children:
      - id: layout
        path: /layout
        type: features
        data:
            section: layout
        blocks:
            - id: features-section-overview
              type: features-section-overview
            - id: layout-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - css-grid
            - flexbox
            - css-multi-column
            - css-writing-modes
            - css-exclusions
            - id: resources-sponsors
              type: resources
              items:
                  - designcode1
                  - frontendmasters-grid

      - id: shapes-and-graphics
        path: /shapes-and-graphics
        type: features
        data:
            section: shapes-and-graphics
        blocks:
            - id: features-section-overview
              type: features-section-overview
            - id: shapes-and-graphics-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - css-shapes
            - object-fit
            - clip-path
            - css-masks
            - blend-modes
            - css-filter-effects
            - id: resources-sponsors
              type: resources
              items:
                  - frontendmasters-svg

      - id: interactions
        path: /interactions
        type: features
        data:
            section: interactions
        blocks:
            - id: features-section-overview
              type: features-section-overview
            - id: interactions-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - css-scroll-snap
            - overscroll-behavior
            - overflow-anchor

      - id: typography
        path: /typography
        type: features
        data:
            section: typography
        blocks:
            - id: features-section-overview
              type: features-section-overview
            - id: typography-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - web-fonts-font-face
            - variable-fonts
            - line-breaking-properties
            - font-variant
            - initial-letter
            - id: resources-sponsors
              type: resources
              items:
                  - frontendmasters-typography

      - id: animations-and-transforms
        path: /animations-and-transforms
        type: features
        data:
            section: animations-and-transforms
        blocks:
            - id: features-section-overview
              type: features-section-overview
            - id: animations-and-transforms-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - css-transitions
            - css-transforms
            - css-animations
            - id: resources-sponsors
              type: resources
              items:
                  - frontendmasters-css

      - id: other-features
        path: /other-features
        type: features
        data:
            section: other-features
        blocks:
            - id: features-section-overview
              type: features-section-overview
              showDescription: true
            - id: other-features-experience-heatmap
              type: heatmap
              subject: features
              heatmapType: experience
            - css-variables
            - support-queries
            - css-containment
            - will-change
            - calc
            - id: resources-sponsors
              type: resources
              items:
                  - designcode2

- id: units-and-selectors
  path: /units-and-selectors
  type: page
  blocks:
      - id: units
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: pseudo-elements
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: combinators
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: tree-document-structure
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: attributes
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: links-urls
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: interaction
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: form-controls
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: resources-sponsors
        type: resources
        items:
            - frontendmasters-code

- id: technologies
  path: /technologies
  type: page
  defaultBlockType: tool
  blocks:
      - id: tools-overview
        type: tools-overview
      - id: tools-scatterplot
        type: tools-scatterplot
  children:
      - id: pre-post-processors
        path: /pre-post-processors
        type: tools
        blocks:
            - id: tools-section-overview
              type: tools-section-overview
            - id: pre-post-processors-experience-heatmap
              type: heatmap
              subject: tools
              heatmapType: experience
            - id: pre-post-processors-salary-heatmap
              type: heatmap
              subject: tools
              heatmapType: salary
            - sass
            - less
            - postcss
            - stylus
            - id: happiness-test
              type: happiness
            - id: resources-sponsors
              type: resources
              items:
                  - frontendmasters-sass

      - id: css-frameworks
        path: /css-frameworks
        type: tools
        blocks:
            - id: tools-section-overview
              type: tools-section-overview
            - id: css-frameworks-experience-heatmap
              type: heatmap
              subject: tools
              heatmapType: experience
            - id: css-frameworks-salary-heatmap
              type: heatmap
              subject: tools
              heatmapType: salary
            - bootstrap
            - materialize-css
            - ant-design
            - semantic-ui
            - bulma
            - foundation
            - uikit
            - tachyons
            - primer
            - tailwind
            - purecss

      - id: methodologies
        path: /methodologies
        type: tools
        blocks:
            - id: tools-section-overview
              type: tools-section-overview
            - id: methodologies-experience-heatmap
              type: heatmap
              subject: tools
              heatmapType: experience
            - id: methodologies-salary-heatmap
              type: heatmap
              subject: tools
              heatmapType: salary
            - bem
            - atomic-css
            - oocss
            - smacss
            - it-css

      - id: css-in-js
        path: /css-in-js
        type: tools
        blocks:
            - id: tools-section-overview
              type: tools-section-overview
            - id: css-in-js-experience-heatmap
              type: heatmap
              subject: tools
              heatmapType: experience
            - id: css-in-js-salary-heatmap
              type: heatmap
              subject: tools
              heatmapType: salary
            - styled-components
            - glamor
            - aphrodite
            - jss
            - styled-jsx
            - radium
            - emotion
            - css-modules
            - id: resources-sponsors
              type: resources
              items:
                  - frontendmasters-react

- id: other-tools
  path: /other-tools
  type: page
  blocks:
      - id: text-editors
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: text-editors-others
        type: horizontal-bar
        dataKey: others
        showDescription: true
        mode: relative
        units: count
      - id: browsers
        type: horizontal-bar
        dataKey: usage
        showDescription: true
        mode: absolute
      - id: browsers-others
        type: horizontal-bar
        dataKey: others
        showDescription: true
        mode: relative
        units: count

- id: environments
  path: /environments
  type: page
  blocks:
      - id: env-browsers
        type: horizontal-bar
        dataKey: environments
        showDescription: true
        mode: absolute
      - id: form-factors
        type: horizontal-bar
        dataKey: environments
        showDescription: true
        mode: absolute
      - id: print-styles
        type: vertical-bar
        dataKey: usage
        bucketKeys: environmentUsage
        showDescription: true
        showLegend: true
      - id: email-styles
        type: vertical-bar
        dataKey: usage
        bucketKeys: environmentUsage
        showDescription: true
        showLegend: true

- id: resources
  path: /resources
  type: page
  blocks:
      - id: blogs-magazines
        type: horizontal-bar
        dataKey: resources
        showDescription: true
        mode: absolute
      - id: blogs-magazines-others
        type: horizontal-bar
        dataKey: others
        showDescription: true
        mode: relative
        units: count
      - id: sites-courses
        type: horizontal-bar
        dataKey: resources
        showDescription: true
        mode: absolute
      - id: sites-courses-others
        type: horizontal-bar
        dataKey: others
        showDescription: true
        mode: relative
        units: count
      - id: podcasts
        type: horizontal-bar
        dataKey: resources
        showDescription: true
        mode: absolute
      - id: podcasts-others
        type: horizontal-bar
        dataKey: others
        showDescription: true
        mode: relative
        units: count
      - id: resources-sponsors
        type: resources
        items:
            - storybook1

- id: opinions
  path: /opinions
  type: page
  blocks:
      - id: easy-to-learn
        type: opinion-scale
      - id: evolving-too-slowly
        type: opinion-scale
      - id: utility-classes
        type: opinion-scale
        showDescription: true
      - id: selector-nesting
        type: opinion-scale
        showDescription: true
      - id: programming-language
        type: opinion-scale
      - id: enjoy-css
        type: opinion-scale
      - id: missing-features
        type: horizontal-bar
        dataKey: features

- id: awards
  path: /awards
  type: page
  blocks:
      - id: feature-adoption
        type: award
      - id: tool-usage
        type: award
      - id: tool-satisfaction
        type: award
      - id: tool-interest
        type: award
      - id: resource-usage
        type: award

- id: conclusion
  path: /conclusion
  type: page
  blocks:
      - id: conclusion
        type: text

- id: support
  path: /support
  type: page
  is_hidden: true

- id: notfound
  path: /404
  type: page
  is_hidden: true
