- id: introduction
  path: /

- id: tshirt
  path: /tshirt

- id: demographics
  path: /demographics
  blocks:
      - id: country
        template: demographicsTemplate
        blockType: ParticipationByCountryBlock
      - id: salary
        template: demographicsTemplate
      - id: workExperience
        template: demographicsTemplate
      - id: companySize
        template: demographicsTemplate
      - id: source
        template: demographicsTemplate
        blockType: HorizontalBarBlock
      - id: gender
        template: demographicsTemplate
        blockType: GenderBlock
      - id: jobTitle
        template: demographicsTemplate
        blockType: HorizontalBarBlock
      - id: cssProficiency
        template: demographicsTemplate
      - id: backendProficiency
        template: demographicsTemplate
      - id: resources-sponsors
        blockType: SponsoredResourcesBlock
        items:
            - frontendmasters-design

- id: features
  path: /features
  children:
      - id: syntax
        path: /syntax
        blocks:
            - id: syntax
              template: pageIntroductionTemplate
              variables:
                  pageId: '${id}'

            - id: destructuring
              template: featureExperienceTemplate

            - id: spread_operator
              template: featureExperienceTemplate

            - id: arrow_functions
              template: featureExperienceTemplate

      - id: language
        path: /language
        blocks:
            - id: language
              template: pageIntroductionTemplate
              variables:
                  pageId: '${id}'

            - id: proxies
              template: featureExperienceTemplate

            - id: async_await
              template: featureExperienceTemplate

            - id: promises
              template: featureExperienceTemplate

            - id: decorators
              template: featureExperienceTemplate

      - id: data_structures
        path: /data-structures
        blocks:
            - id: data_structures
              template: pageIntroductionTemplate
              variables:
                  pageId: '${id}'

            - id: maps
              template: featureExperienceTemplate

            - id: sets
              template: featureExperienceTemplate

            - id: typed_arrays
              template: featureExperienceTemplate

            - id: array_prototype_flat
              template: featureExperienceTemplate

      - id: browser_apis
        path: /browser-apis
        blocks:
            - id: browser_apis
              template: pageIntroductionTemplate
              variables:
                  pageId: '${id}'

            - id: fetch
              template: featureExperienceTemplate

            - id: i18n
              template: featureExperienceTemplate

            - id: local_storage
              template: featureExperienceTemplate

            - id: service_workers
              template: featureExperienceTemplate

            - id: web_animations
              template: featureExperienceTemplate

            - id: web_audio
              template: featureExperienceTemplate

            - id: web_components
              template: featureExperienceTemplate

            - id: webgl
              template: featureExperienceTemplate

            - id: webrtc
              template: featureExperienceTemplate

            - id: websocket
              template: featureExperienceTemplate

            - id: web_speech
              template: featureExperienceTemplate

            - id: webvr
              template: featureExperienceTemplate

      - id: other_features
        path: /other-features
        blocks:
            - id: features_other_features
              template: pageIntroductionTemplate
              variables:
                  pageId: '${id}'

            - id: pwa
              template: featureExperienceTemplate

            - id: wasm
              template: featureExperienceTemplate

- id: front_end_frameworks
  path: /front-end-frameworks
  template: toolSectionTemplate
  children:
      - id: react
        template: toolPageTemplate
      - id: vue
        template: toolPageTemplate
      - id: angular
        template: toolPageTemplate
      - id: preact
        template: toolPageTemplate
      - id: ember
        template: toolPageTemplate
      - id: svelte
        template: toolPageTemplate
      # - id: frontend-other
      #   template: toolOtherTemplate
      # - id: frontend-conclusion
      #   template: toolConclusionTemplate

- id: data_layer
  path: /data-layer
  template: toolSectionTemplate
  children:
      - id: redux
        template: toolPageTemplate
      - id: apollo
        template: toolPageTemplate
      - id: graphql
        template: toolPageTemplate
      - id: relay
        template: toolPageTemplate
      - id: mobx
        template: toolPageTemplate
      # - id: datalayer-other
      #   template: toolOtherTemplate
      # - id: datalayer-conclusion
      #   template: toolConclusionTemplate

- id: back_end_frameworks
  path: /back-end
  template: toolSectionTemplate
  children:
      - id: express
        template: toolPageTemplate
      - id: nextjs
        template: toolPageTemplate
      - id: koa
        template: toolPageTemplate
      - id: meteor
        template: toolPageTemplate
      - id: sails
        template: toolPageTemplate
      - id: feathers
        template: toolPageTemplate
      - id: nuxt
        template: toolPageTemplate
      - id: gatsby
        template: toolPageTemplate
      # - id: backend-other
      #   template: toolOtherTemplate
      # - id: backend-conclusion
      #   template: toolConclusionTemplate

- id: testing
  path: /testing
  template: toolSectionTemplate
  children:
      - id: jest
        template: toolPageTemplate
      - id: mocha
        template: toolPageTemplate
      - id: storybook
        template: toolPageTemplate
      - id: cypress
        template: toolPageTemplate
      - id: enzyme
        template: toolPageTemplate
      - id: ava
        template: toolPageTemplate
      - id: jasmine
        template: toolPageTemplate
      - id: puppeteer
        template: toolPageTemplate
      # - id: testing-other
      #   template: toolOtherTemplate
      # - id: testing-conclusion
      #   template: toolConclusionTemplate

- id: mobile_desktop
  path: /mobile-desktop
  template: toolSectionTemplate
  children:
      - id: electron
        template: toolPageTemplate
      - id: react-native
        template: toolPageTemplate
      - id: native-apps
        template: toolPageTemplate
      - id: cordova
        template: toolPageTemplate
      - id: ionic
        template: toolPageTemplate
      - id: nwjs
        template: toolPageTemplate
      - id: expo
        template: toolPageTemplate
      # - id: mobiledesktop-other
      #   template: toolOtherTemplate
      # - id: mobiledesktop-conclusion
      #   template: toolConclusionTemplate

- id: other-tools
  path: /other-tools
  blocks:
      - id: utilities
        template: otherToolsTemplate
      - id: utilities_others
        template: otherToolsTemplate
        mode: relative
        units: count
      - id: text_editors
        template: otherToolsTemplate
      - id: text_editors_others
        template: otherToolsTemplate
        mode: relative
        units: count
      - id: browsers
        template: otherToolsTemplate
      - id: browsers_others
        template: otherToolsTemplate
        mode: relative
        units: count
      - id: build_tools
        template: otherToolsTemplate
      - id: build_tools_others
        template: otherToolsTemplate
        mode: relative
        units: count
      - id: non_js_languages
        template: otherToolsTemplate
      - id: non_js_languages_others
        template: otherToolsTemplate
        mode: relative
        units: count

- id: resources
  path: /resources
  blocks:
      - id: blogs_magazines
        template: resourcesTemplate
      - id: blogs_magazines_others
        template: resourcesTemplate
        mode: relative
        units: count
      - id: sites_courses
        template: resourcesTemplate
      - id: sites_courses_others
        template: resourcesTemplate
        mode: relative
        units: count
      - id: podcasts
        template: resourcesTemplate
      - id: podcasts_others
        template: resourcesTemplate
        mode: relative
        units: count
      - id: resources-sponsors
        blockType: SponsoredResourcesBlock
        items:
            - storybook1

- id: opinions
  path: /opinions
  blocks:
      - id: opinions-introduction
        template: pageIntroductionTemplate
        variables:
            pageId: '${id}'
      - id: js_moving_in_right_direction
        template: opinionTemplate
        bucketKeysName: opinions
      - id: building_js_apps_overly_complex
        template: opinionTemplate
        bucketKeysName: opinions
      - id: js_over_used_online
        template: opinionTemplate
        bucketKeysName: opinions
      - id: enjoy_building_js_apps
        template: opinionTemplate
        bucketKeysName: opinions
      - id: would_like_js_to_be_main_lang
        template: opinionTemplate
        bucketKeysName: opinions
      - id: js_ecosystem_changing_to_fast
        template: opinionTemplate
        bucketKeysName: opinions
      # - id: missing-features
      #   blockType: HorizontalBarBlock
      #   dataKey: features

- id: awards
  path: /awards
  blocks:
      - id: feature_adoption
        blockType: AwardBlock
      - id: tool_usage
        blockType: AwardBlock
      - id: tool_satisfaction
        blockType: AwardBlock
      - id: tool_interest
        blockType: AwardBlock
      - id: resource_usage
        blockType: AwardBlock

- id: conclusion
  path: /conclusion
  blocks:
      - id: conclusion
        blockType: TextBlock

# - id: support
#   path: /support
#   blockType: page
#   is_hidden: true

- id: notfound
  path: /404
  is_hidden: true
