---
title: State of JavaScript 2018
theme:
  href: https://api.typeform.com/themes/Gp3idU
workspace:
  href: https://api.typeform.com/workspaces/QhHBZg
settings:
  is_public: false
  is_trial: true
  language: en
  progress_bar: percentage
  show_progress_bar: true
  show_typeform_branding: true
  meta:
    allow_indexing: true
    description: The annual survey about the current State of JavaScript
    image:
      href: https://images.typeform.com/images/gY3LRBvFgzs6
welcome_screens:
- title: |-
    Thanks for taking this survey! Together, maybe we'll be able to figure out this JavaScript thing once and for all!

    Also, we know this survey seems long, but it's mostly the same questions repeated for different frameworks and libraries. Most people only take around *15 minutes* to fill it in.
  properties:
    show_button: true
    button_text: Let's Get This Started
  attachment:
    type: image
    href: https://images.typeform.com/images/gY3LRBvFgzs6
thankyou_screens:
- title: |-
    Thanks for completing this typeform
    Now *create your own* — it's free, easy, & beautiful
  properties:
    show_button: true
    share_icons: false
    button_mode: redirect
    button_text: Create a *typeform*
    redirect_url: https://admin.typeform.com/powered-by?utm_campaign=S5iLk9&utm_source=typeform.com-4189488-Basic&utm_medium=typeform&utm_content=typeform-thankyoubutton&utm_term=EN
  attachment:
    type: image
    href: https://images.typeform.com/images/2dpnUBBkz2VN
fields:
- title: |-

    Table Of Contents

    1. Features – Language, syntax…
    2. Tools – libraries, frameworks…
    4. Resources – Blogs, podcasts…
    5. Opinions – How you feel about JavaScript.
    6. About You – Experience, salary…

  properties:
    hide_marks: true
  type: statement

logic: []

#  note: rather than test if the value is equal to "undefined" we need to 
#  test if it's empty. Uncomment when we find a way to do that, until then always show
#  the country and city fields.

# logic: 
#   - type: field
#     ref: youremail
#     actions:
#       - action: jump
#         details: 
#           to:
#             type: field
#             value: yourcountry
#         condition:
#           op: equal
#           vars:
#             - type: hidden
#               value: location
#             - type: constant
#               value: undefined
#       - action: jump
#         details: 
#           to:
#             type: field
#             value: othercomments
#         condition:
#           op: always
#           vars: []

hidden: 
  - location
  - device
  - browser
  - version
  - os
  - city
  - referrer
  - source
  - gaid